---
- name: Template the iptables rules
  ansible.builtin.template:
    src: iptables.conf
    dest: /etc/iptables.conf
    owner: root
    group: root
    mode: "0644"

- name: Check the location of iptables-restore
  register: "iptables_restore"
  changed_when: no
  failed_when: "iptables_restore.stdout | length == 0"
  ansible.builtin.command:
    cmd: "which iptables-restore"

- name: Template the iptables systemd service
  ansible.builtin.template:
    src: systemd/iptables.service.j2
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and start the iptables service
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: yes
