---
- name: Ensure the root group exists
  ansible.builtin.group:
    name: "{{ sudo_group }}"
    state: present

- name: Allow sudo group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ sudo_group }}"
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: enable_passwordless_sudo | default(False)

- name: Create a login user
  changed_when: false
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password | string | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - users
    state: present
    append: true
    shell: "{{ user_shell }}"
  when: enable_username_creation | default(False)

- name: Ensure group "{{ username }}" exists
  ansible.builtin.group:
    name: "{{ username }}"
    state: present
  when: enable_username_creation | default(False)

- name: Check if the Ansible playbook is copied to the new user directory
  ansible.builtin.stat:
    path: "/home/{{ username }}/ansible-easy-vpn"
  register: playbook_copied

- name: Add the direnv hook to {{ username }}`s bashrc
  ansible.builtin.blockinfile:
    path: /home/{{ username }}/.bashrc
    block: |
      eval "$(direnv hook bash)"
      direnv allow $HOME/ansible-easy-vpn

- name: Handle user directory and playbook folder
  when: not playbook_copied.stat.exists
  block:
    - name: Copy the Ansible playbook to the new user
      ansible.posix.synchronize:
        src: "/{{ lookup('env', 'HOME') }}/ansible-easy-vpn"
        dest: "/home/{{ username }}"

    - name: Fix the user's venv copy
      changed_when: true
      ansible.builtin.shell:
        cmd: 'cd /home/{{ username }}/.venv && sed -i "s|/root/ansible-easy-vpn|/home/{{ username }}/ansible-easy-vpn|g" *'

    - name: Chmod the ansible-easy-vpn directory
      ansible.builtin.file:
        path: "/home/{{ username }}/ansible-easy-vpn"
        state: directory
        mode: 0755
        owner: "{{ username }}"
        group: "{{ username }}"
        recurse: yes
      when: not enable_username_creation | default(False)

    - name: Chmod the user home directory
      ansible.builtin.file:
        path: "/home/{{ username }}"
        state: directory
        mode: 0755
        owner: "{{ username }}"
        group: "{{ username }}"
        recurse: yes
      when: enable_username_creation | default(False)
