- name: Install UFW
  package:
    name: ufw
    state: present

- name: Enable UFW logging
  ufw:
    logging: on

- name: Allow the defined ports
  ufw:
    rule: allow
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  with_items:
    - "{{ ufw_ports }}"

- name: Deny everything else and enable UFW
  ufw:
    state: enabled
    policy: deny
