---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/authelia"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Copy the main config
  ansible.builtin.template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/authelia/configuration.yml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart authelia

- name: Copy the users database
  changed_when: false
  ansible.builtin.template:
    src: users_database.yml.j2
    dest: "{{ docker_dir }}/authelia/users_database.yml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart authelia

- name: Make sure the Redis container is created and running
  register: redis_result
  retries: 5
  until: redis_result is succeeded
  community.general.docker_container:
    name: "redis"
    image: "redis:alpine"
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.3
    pull: yes
    state: "started"
    restart_policy: unless-stopped

- name: Make sure the Authelia container is created and running
  register: authelia_result
  retries: 5
  until: authelia_result is succeeded
  community.general.docker_container:
    name: "authelia"
    image: "authelia/authelia:{{ authelia_version }}"
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.4
    pull: yes
    state: "started"
    volumes:
      - "{{ docker_dir }}/authelia:/config"
    restart_policy: unless-stopped

- name: Add a 2FA alias shortcut command
  ansible.builtin.blockinfile:
    path: "/usr/bin/show_2fa"
    create: yes
    owner: root
    mode: 0755
    state: present
    block: |
      #! /usr/bin/env bash
      sudo cat {{ docker_dir }}/authelia/notification.txt
