---
- name: get public IP
  ipify_facts:

- name: Make sure the Wireguard container is created and running
  docker_container:
    name: "wg-easy"
    image: "weejewel/wg-easy"
    pull: yes
    networks:
      - name: wg_network
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    state: "started"
    env:
      "WG_HOST": "{{ host }}"
      "PEERS": "{{ ', '.join(wireguard_peers) }}"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_dir }}/wg-easy:/etc/wireguard"
    restart_policy: unless-stopped
